### ISSUE TITLE
Descripción bug

### ISSUE THREAD

**Issue by TuQmano** [Nicolas-Schmidt/puy#1]
Tenes la desc de la variable siguiente

https://github.com/Nicolas-Schmidt/puy/blob/4db39dfe0d0f9eabdaabc6094f1839d32c87b571/README.Rmd#L52

**Comment by TuQmano** [comment]
Algo similar en esta doc  @Nicolas-Schmidt   https://github.com/Nicolas-Schmidt/puy/blob/4db39dfe0d0f9eabdaabc6094f1839d32c87b571/R/legislaturas.R#L16

(Pectacular idea. Ya plagiaremos =P )

**Comment by Nicolas-Schmidt** [comment]
> Tenes la desc de la variable siguiente
> 
> https://github.com/Nicolas-Schmidt/puy/blob/4db39dfe0d0f9eabdaabc6094f1839d32c87b571/README.Rmd#L52

@TuQmano ohh excelente!, gracias!

**Comment by Nicolas-Schmidt** [comment]
> Algo similar en esta doc @Nicolas-Schmidt
> 
> https://github.com/Nicolas-Schmidt/puy/blob/4db39dfe0d0f9eabdaabc6094f1839d32c87b571/R/legislaturas.R#L16
> 
> (Pectacular idea. Ya plagiaremos =P )

Oh no, no de nuevo decía!  #Gracias
ja, dele nomás tranquilo y agarre lo que necesite que no hay plagio!
