### ISSUE TITLE
Typo en título

### ISSUE THREAD

**Issue by bcattaneo** [Nicolas-Schmidt/puy#2]
Tiene un typo acá:
https://github.com/Nicolas-Schmidt/puy/blob/5482d1c703265a8e5927f1705bed99684b626b7c/docs/index.html#L8

Entiendo se genera desde acá:
https://github.com/Nicolas-Schmidt/puy/blob/1283102dda1fde18b6a484f38ce74c12f71c0617/DESCRIPTION#L3

**Comment by Nicolas-Schmidt** [comment]
Hola!, efectivamente, muchas gracias por detectarlo y notificarlo! ya quedó resuelto.
